site_name: HuangFuSL's Blog
repo_name: HuangFuSL/HuangFuSL.github.io
repo_url: https://github.com/HuangFuSL/HuangFuSL.github.io
edit_uri: https://github.com/HuangFuSL/HuangFuSL.github.io/edit/main/docs

theme:
  name: material
  custom_dir: overrides
  language: zh
  palette:  # 颜色
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
  font:
    code: Source Code Pro
    text: PingFang SC
  favicon: img/favicon.png
  icon:
    # logo: material/book-variant
    logo: bootstrap/journal-bookmark-fill
    repo: fontawesome/brands/git-alt
extra:
  pagetime: 'on'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/HuangFuSL
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/huangfusl
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/huangfusl/
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/huang-fu-shuo-long
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/387905326
watch:
  - data
  - main
plugins:
  - search:
      separator: '[\s\u200b\-]'
  - awesome-pages
  - git-revision-date
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - macros
  - mkdocs-jupyter:
      include_source: true
      execute: true
markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.keys
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.extra
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tilde
  - attr_list
  - neoteroi.timeline
  - neoteroi.cards
  - neoteroi.spantable

extra_css:
  - https://www.neoteroi.dev/mkdocs-plugins/css/neoteroi.css
  - css/button.css
  - css/colors.css
  - css/codecolor.css
  - css/codedef_custom.css
  - css/admonitions.css
  - css/images.css
  - css/jupyter.css
  - css/timeline.css
  - css/aoe.css


extra_javascript:
  - 'https://cdn.bootcdn.net/ajax/libs/blueimp-md5/2.18.0/js/md5.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - js/love.js