name: Build Documentation

on:
  # To be reused by other workflows
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      deploy:
        required: true
        type: boolean

jobs:
  build:
    name: Build documentation
    runs-on: self-hosted
    steps:

      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          path: '.'
          ref: 'main'

      - name: Test
        if: inputs.deploy == false
        run: |
          make build PYTHON=~/${{ inputs.build-type }}/bin/python3 XELATEX=~/.local/texlive/2023/bin/x86_64-linux/xelatex DVISVGM=~/.local/texlive/2023/bin/x86_64-linux/dvisvgm TEXINPUTS=$PWD/third_party//:

      - name: Deploy
        if: inputs.deploy
        run: |
          git checkout main && git pull
          make deploy PYTHON=~/${{ inputs.build-type }}/bin/python3 XELATEX=~/.local/texlive/2023/bin/x86_64-linux/xelatex DVISVGM=~/.local/texlive/2023/bin/x86_64-linux/dvisvgm TEXINPUTS=$PWD/third_party//:
