name: Build Documentation

on:
  # To be reused by other workflows
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      deploy:
        required: true
        type: boolean
      head-ref:
        required: true
        type: string

jobs:
  build:
    name: Build documentation
    runs-on: self-hosted
    steps:

      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          path: '.'
          ref: ${{ github.event.inputs.head-ref }}

      - name: Test
        if: inputs.deploy == false
        run: |
          make build PYTHON=~/${{ inputs.build-type }}/bin/python3 TEXINPUTS=$PWD/third_party//: PATH=~/.local/texlive/2023/bin/x86_64-linux:$PATH

      - name: Deploy
        if: inputs.deploy
        run: |
          git checkout main && git pull
          make deploy PYTHON=~/${{ inputs.build-type }}/bin/python3 TEXINPUTS=$PWD/third_party//: PATH=~/.local/texlive/2023/bin/x86_64-linux:$PATH
