name: Build Documentation

on:
  # To be reused by other workflows
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      deploy:
        required: true
        type: boolean

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    container: ghcr.io/huangfusl/blog-env:${{ inputs.build-type }}
    steps:

      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      # - name: Test
      #   if: inputs.deploy == false
      #   env:
      #     TEXINPUTS: "$PWD/third_party//:"
      #   run: |
      #     chown -R root:root $PWD
      #     . /root/venv/bin/activate
      #     python3 ./ci/deploy.py --dry-run

      # - name: Save artifact
      #   uses: actions/upload-artifact@v3
      #   if: inputs.deploy == false
      #   with:
      #     name: github.head_ref
      #     path: |
      #       ./build

      - name: Set up Deploy Environment
        # if: inputs.deploy
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy
        # if: inputs.deploy
        env:
          TEXINPUTS: "$PWD/third_party//:"
        run: |
          chown -Rv root:root $PWD
          . /root/venv/bin/activate
          git pull
          python3 ./ci/deploy.py
