name: Build Documentation

on:
  push:
    branches: [main]

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Restoring packages
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.local
          key: ${{ steps.python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt --user --no-warn-script-location

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: scheme-full

      - name: Install GhostScript
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript -y

      - name: Deploy
        env:
          TEXINPUTS: "${{ github.workspace }}/third_party//:"
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull
          python3 ./ci/deploy.py

      - name: Update Metrics
        run: gh workflow run metric.yml
