name: Build Documentation

on:
  # To be reused by other workflows
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      deploy:
        required: true
        type: boolean

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/huangfusl/blog-env:${{ inputs.build-type }}
      options: --user root
    steps:

      - name: Checkout Head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          path: '.'
          ref: ${{ github.head_ref }}

      - name: Test
        if: inputs.deploy == false
        env:
          TEXINPUTS: "$PWD/third_party//:"
        run: |
          cd $GITHUB_WORKSPACE
          chown -R root:root $PWD
          . /root/venv/bin/activate
          make -f ./docs/makefile build

      - name: Set up Deploy Environment
        if: inputs.deploy
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy
        if: inputs.deploy
        env:
          TEXINPUTS: "$PWD/third_party//:"
        run: |
          cd $GITHUB_WORKSPACE
          chown -R root:root $PWD
          . /root/venv/bin/activate
          git checkout main && git pull
          make -f ./docs/makefile deploy
