name: Build Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup texlive
        run: |
          sudo apt install texlive-base texlive-extra-utils texlive-lang-chinese
          sudo apt install texlive-latex-base texlive-math-extra
          sudo apt install texlive-latex-extra texlive-latex-recommended



      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy
        env:
          GITALK_SECRET: ${{ secrets.GITALK_SECRET }}
        run: |
          git pull
          python3 ./ci/deploy.py
