name: Build Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]

env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Restoring packages
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.local
          key: ${{ steps.python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt --user --no-warn-script-location

      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: scheme-full

      - name: Deploy
        run: |
          git pull
          python3 ./ci/deploy.py

      - name: Update Metrics
        run: gh workflow run metric.yml
