name: Deploy Documentation

on:
  push:
    branches: [main]
    # Exclude dependabot
    paths:
      - 'docs/**'
      - 'main/**'
      - 'overrides/**'
      - 'third_party/**'
      - 'ci/**'
      - 'README.md'
      - 'mkdocs.yml'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy documentation
    runs-on: self-hosted
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
          path: '.'
      - name: Build and deploy
        run: |
          git checkout main && git pull
          make deploy PYTHON=~/build/bin/python3 TEXINPUTS=$PWD/third_party//: PATH=~/.local/texlive/2023/bin/x86_64-linux:$PATH

  metrics:
    name: Update metrics
    needs: deploy
    uses: ./.github/workflows/metric.yml
    secrets: inherit
