name: Deploy Documentation

on:
  push:
    branches: [main]
    # Exclude dependabot
    paths:
      - '.github/**'
      - 'docs/**'
      - 'main/**'
      - 'overrides/**'
      - 'third_party/**'
      - 'README.md'
      - 'mkdocs.yml'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    name: Deploy documentation
    uses: ./.github/workflows/build.yml
    with:
      build-type: build
      deploy: true
    secrets: inherit

  latex:
    name: Compile LaTeX files
    needs: deploy
    uses: ./.github/workflows/latex.yml
    secrets: inherit

  metrics:
    name: Update metrics
    needs: deploy
    uses: ./.github/workflows/metric.yml
    secrets: inherit
