name: Build Docker Image
on:
  schedule:
    - cron: '0 8 1/2 * *'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up texlive
        run: |
          sudo apt install texlive-base texlive-extra-utils texlive-lang-chinese
          sudo apt install texlive-latex-base texlive-latex-extra
          sudo apt install texlive-latex-recommended texlive-xetex
      
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Generate SVG
        run: |
          git pull
          python3 ./ci/convert.py

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: huangfusl/huangfusl.github.io:latest
