name: Test pull request

on:
  pull_request:

jobs:
  pylint:
    name: Lint code
    runs-on: ubuntu-latest
    if:
      (
        contains(github.event.pull_request.labels.*.name, 'dependencies') == false &&
        github.base_ref == 'main'
      ) ||
      contains(github.event.pull_request.labels.*.name, 'ci') == true
    steps:
    - name: Checkout Main
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --rcfile=.pylintrc --fail-under=9

  test_code_block:
    name: Test code block
    runs-on: ubuntu-latest
    if:
      (
        contains(github.event.pull_request.labels.*.name, 'dependencies') == false &&
        github.base_ref == 'main'
      ) ||
      contains(github.event.pull_request.labels.*.name, 'ci') == true
    container:
      image: ghcr.io/huangfusl/blog-env:build
      options: --user root
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4

      - name: Test
        run:
          # Exec doctest on all md files exclude pyguide.md
          python3 -m doctest $(find . -name '*.md' -not -name 'pyguide.md') -v -o ELLIPSIS -o IGNORE_EXCEPTION_DETAIL

  test:
    name: Test documentation
    if:
      (
        contains(github.event.pull_request.labels.*.name, 'dependencies') == false &&
        github.base_ref == 'main'
      ) ||
      contains(github.event.pull_request.labels.*.name, 'ci') == true
    uses: ./.github/workflows/build.yml
    with:
      build-type: build
      deploy: false
