name: Test pull request

on:
  pull_request:
    # Commented out for testing
    # branches: [main]

jobs:
  pylint:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') == false
    container: ghcr.io/huangfusl/blog-env:2023
    steps:
    - name: Checkout Main
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        . /root/venv/bin/activate
        python3 -m pip install --upgrade pip
        pip3 install pylint

    - name: Analysing the code with pylint
      run: |
        . /root/venv/bin/activate
        pylint $(git ls-files '*.py') --rcfile=.pylintrc --fail-under=9

  test_code_block:
    name: Test code block
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') == false
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run:
          . /root/venv/bin/activate
          python3 ./ci/test_code_block.py

  test:
    name: Test documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Test
        env:
            TEXINPUTS: "${{ github.workspace }}/third_party//:"
        run: |
          . /root/venv/bin/activate
          python3 ./ci/deploy.py --dry-run

      - name: Save artifact
        uses: actions/upload-artifact@v3
        if: contains(github.event.pull_request.labels.*.name, 'dependencies') == false
        with:
          name: ${{ github.head_ref }}
          path: |
            ./build
