name: Test pull request

on:
  pull_request:
    # Commented out for testing
    # branches: [main]

jobs:
  pylint:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') == false
    steps:
    - name: Checkout Main
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --rcfile=.pylintrc --fail-under=9

  test_code_block:
    name: Test code block
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') == false
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3
        uses: actions/setup-python@v4
        id: python
        with:
          python-version: '3.x'
          cache: 'pip'

      - uses: actions/cache@v3
        id: cache
        with:
          path: ~/.local
          key: ${{ steps.python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt --user --no-warn-script-location

      - name: Test
        run:
          python3 ./ci/test_code_block.py

  test:
    name: Test documentation
    runs-on: ubuntu-latest
    container: ghcr.io/huangfusl/blog-env:2023
    if: contains(github.event.pull_request.labels.*.name, 'dependencies') == false
    steps:

      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Test
        env:
            TEXINPUTS: "${{ github.workspace }}/third_party//:"
        run: |
          chown -R root:root ${{ github.workspace }}
          . /root/venv/bin/activate
          python3 ./ci/deploy.py --dry-run

      - name: Save artifact
        uses: actions/upload-artifact@v3
        if: contains(github.event.pull_request.labels.*.name, 'dependencies') == false
        with:
          name: ${{ github.head_ref }}
          path: |
            ./build
