name: Test pull request

on:
  pull_request:

jobs:
  test:
    name: Test documentation
    if:
      (
        contains(github.event.pull_request.labels.*.name, 'dependencies') == false &&
        github.base_ref == 'main'
      ) ||
      contains(github.event.pull_request.labels.*.name, 'ci') == true
    runs-on: self-hosted
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'true'
          path: '.'
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build and deploy
        run: |
          make build PYTHON=~/build/bin/python3 TEXINPUTS=$PWD/third_party//: PATH=~/.local/texlive/2023/bin/x86_64-linux:$PATH

      - name: Merge PR
        if: contains(github.event.pull_request.labels.*.name, 'ready') == true
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh pr merge ${{ github.event.number }} -d -R ${{ github.repository }} --merge