name: Test pull request

on:
  pull_request:

jobs:
  pylint:
    name: Lint code
    runs-on: ubuntu-latest
    if:
      (
        contains(github.event.pull_request.labels.*.name, 'dependencies') == false &&
        github.base_ref == 'main'
      ) ||
      contains(github.event.pull_request.labels.*.name, 'ci') == true
    steps:
    - name: Checkout Head
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --rcfile=.pylintrc --fail-under=9

  test_code_block:
    name: Test code block
    runs-on: self-hosted
    if:
      (
        contains(github.event.pull_request.labels.*.name, 'dependencies') == false &&
        github.base_ref == 'main'
      ) ||
      contains(github.event.pull_request.labels.*.name, 'ci') == true
    steps:
      - name: Checkout Head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test
        run:
          make test-code-block

  test:
    name: Test documentation
    if:
      (
        contains(github.event.pull_request.labels.*.name, 'dependencies') == false &&
        github.base_ref == 'main'
      ) ||
      contains(github.event.pull_request.labels.*.name, 'ci') == true
    runs-on: self-hosted
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'true'
          path: '.'
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build and deploy
        run: |
          make build PYTHON=~/build/bin/python3 TEXINPUTS=$PWD/third_party//: PATH=~/.local/texlive/2023/bin/x86_64-linux:$PATH
