name: Test pull request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test documentation
        uses: xu-cheng/texlive-action/small@v1
        with:
          run: |
            apk add python3 py3-pip
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            python3 ./ci/deploy.py --dry-run